# Generated by Django 6.0.3 on 2026-03-13 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VideoAccess',
        ),
    ]
